#   This .travis.yml works to check "this" repository, namely `common_travis`. Do not get confused with the check of "client" repositories (repos that use travis configs in this repo).
sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc
env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
  matrix:
    - CI_ROS_DISTRO="indigo" DEB_REPOSITORY=http://packages.ros.org/ros/ubuntu
    - CI_ROS_DISTRO="indigo" DEB_REPOSITORY=http://packages.ros.org/ros-shadow-fixed/ubuntu
matrix:
  allow_failures:
    - env: CI_ROS_DISTRO="jade"   BIN_REPOSITORY=http://packages.ros.org/ros/ubuntu
    - env: CI_ROS_DISTRO="jade"   BIN_REPOSITORY=http://packages.ros.org/ros-shadow-fixed/ubuntu
notifications:
  email:
    recipients:
      - iiysaito@opensource-robotics.tokyo.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
install:
  - sudo sh -c "echo \"deb ${DEB_REPOSITORY} `lsb_release -cs` main\" > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-catkin-tools
  - sudo rosdep init
  - rosdep update
  # Use rosdep to install all dependencies (including ROS itself)
  - rosdep install --from-paths $TRAVIS_BUILD_DIR -i -y --rosdistro $CI_ROS_DISTRO
script:  # What to do here with this particular repo?
#  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
